# Generated by Django 3.0.7 on 2020-07-03 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_auto_20200703_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('salary', models.IntegerField()),
                ('grade', models.CharField(max_length=64)),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('portfolio', models.CharField(max_length=64)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='jobs.Speciality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
