# Generated by Django 3.0.7 on 2020-07-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='MEDIA_COMPANY_IMAGE_DIR'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='picture',
            field=models.ImageField(upload_to='MEDIA_SPECIALITY_IMAGE_DIR'),
        ),
    ]
